---
    name: Push docker image to Docker Hub

    on:
      push:
        branches:
          - master

    jobs:
        build:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout code
                  uses: actions/checkout@v2
                - name: Setting up docker buildx
                  uses: docker/setup-buildx-action@v3
                - name: Login to DockerHub
                  uses: docker/login-action@v3
                  with:
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                - name: Build and push Bun App
                  uses: docker/build-push-action@v6
                  with:
                    context: .
                    push: true
                    tags: |
                        ${{ secrets.USERNAME }}/bun-app:latest
                        ${{ secrets.USERNAME }}/bun-app:${{ github.sha }}
                    
                - name: Build and push Bun test
                  uses: docker/build-push-action@v6
                  with:
                    context: ./tests/.
                    push: true
                    tags: |
                        ${{ secrets.USERNAME }}/bun-app-test:latest
                        ${{ secrets.USERNAME }}/bun-app-test:${{ github.sha }}
